development:
  stripe_publishable_key: pk_test_51HM1fHL43IOyyC10MiiKqGQFl9pAyI9Ixmh1LMu9c946V8XRG14bh9c8A99biTfH1xq6SiOXNRI6cFAB11aEXWvM00KCqcULJT
  stripe_secret_key:      sk_test_51HM1fHL43IOyyC10VStKy6AXzFOuhuk4yJP2s4Un4XwBRy2HMHu1u9F1p0TtfIqDMYaM7GDqqvwwaBvisSWgPF1A00C1BRYuRs